[package]
name = "hello-rust"
version = "0.1.0"
authors = ["vince"]
edition = "2018"

[dependencies]
rusqlite = {version="0.23.1", features=["bundled"]}
time = "0.2.12"
chrono = "0.4.6"
guid-create = "0.1.1"
meval = "0.2"
regex = "1.4.2"
web-view = "0.7.2"
tinyfiledialogs = "3.3.10"
unicode-segmentation = "1.7.1"