[package]
name = "money_manager"
version = "0.5.0"
authors = ["Vince <vince@vinceworks.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
serde_json = "1.0.85"
serde_repr = "0.1.9"
regex = "1.6.0"
unicode-segmentation = "1.9.0"
format_num = "0.1.0"
base64 = "0.13.0"
rand = "0.8.5"
serde = { version = "1.0.148", features = ["derive"] }
serde-wasm-bindgen = "0.4.5"
#Required, because the indirect reference needs to function in a JavaScript environment
getrandom = { version = "0.2.8", features = ["js"] }

[dependencies.chrono]
version = "0.4.22"
features = ["serde", "wasmbind"]

[dependencies.serde_derive]
version = "1.0.144"


[dependencies.uuid]
version = "1.1.2"
features = [
  "serde", 
  "v4",
  #"wasm-bindgen",
]

[dependencies.wasm-bindgen]
version = "0.2.83"
features = [
  "serde-serialize",
]

[dependencies.web-sys]
version = "0.3.60"
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
  "CssStyleSheet",
  "StyleSheet",
  "HtmlInputElement",
  "FileList",
  "HtmlHeadElement",
  "HtmlDocument",
  "HtmlButtonElement",
  "FileReader",
  "File",
  "Blob",
  "ProgressEvent",
  "ErrorEvent",
  "CssStyleDeclaration",
  "DomStringMap",
  "HtmlAnchorElement",
  "DomTokenList",
  "HtmlTextAreaElement",
  "HtmlSelectElement",
  "HtmlOptionsCollection",
  "HtmlDataListElement",
  "HtmlOptionElement",
  "KeyboardEvent",
  ]

[dependencies.js-sys]
version = "0.3.60"
features = [
  
]

[lib]
crate-type =["cdylib"]
