[package]
name = "money_manager"
version = "0.1.0"
authors = ["Vince <vince@vinceworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.69"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'CssStyleSheet',
  'StyleSheet',
  'HtmlInputElement',
  'FileList',
  'HtmlHeadElement',
  'HtmlDocument',
  'HtmlButtonElement',
  ]

[dependencies.js-sys]
version = "0.3.46"
features = [
  
]

[lib]
crate-type =["cdylib"]
