[package]
name = "money_manager"
version = "0.1.0"
authors = ["Vince <vince@vinceworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.6"
serde_json = "1.0.61"
serde_repr = "0.1.6"
regex = "1.4.3"
unicode-segmentation = "1.7.1"
format_num = "0.1.0"

[dependencies.chrono]
version = "0.4.19"
features = ["serde", "wasmbind"]

[dependencies.serde_derive]
version = "1.0.123"

[dependencies.serde]
version = "1.0.123"
features = [
  "derive",
]

[dependencies.uuid]
version = "0.8"
features = [
  "serde", 
  "v4",
  "wasm-bindgen",
]


[dependencies.wasm-bindgen]
version = "0.2.70"
features = [
  "serde-serialize",
]

[dependencies.web-sys]
version = "0.3.4"
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
  "CssStyleSheet",
  "StyleSheet",
  "HtmlInputElement",
  "FileList",
  "HtmlHeadElement",
  "HtmlDocument",
  "HtmlButtonElement",
  "FileReader",
  "File",
  "Blob",
  "ProgressEvent",
  "ErrorEvent",
  "CssStyleDeclaration",
  "DomStringMap",
  "HtmlAnchorElement",
  "DomTokenList",
  "HtmlTextAreaElement",
  "HtmlSelectElement",
  "HtmlOptionsCollection",
  "HtmlDataListElement",
  "HtmlOptionElement",
  ]

[dependencies.js-sys]
version = "0.3.46"
features = [
  
]

[lib]
crate-type =["cdylib"]
